
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE'
export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT'
export const AUTH_USER_SIGNUP = 'AUTH_USER_SIGNUP'
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT'
export const AUTH_GET_USER_CREDENTIALS = 'AUTH_GET_USER_CREDENTIALS'
export const AUTH_SET_REDIRECT_PATH = 'AUTH_SET_REDIRECT_PATH'
export const AUTH_UPDATE_USER = 'AUTH_UPDATE_USER'
export const AUTH_UPDATE_SUCCESS = 'AUTH_UPDATE_SUCCESS'

export const SET_USER_INFORMATION = 'SET_USER_INFORMATION'

